In [17]:
import pandas as pd

# denver airbnb review data
reviews_gz_df = pd.read_csv('reviews.csv.gz', compression='gzip', header=0, sep=',', quotechar='"')
reviews_gz_df.head(5)

,listing_id,id,date,reviewer_id,reviewer_name,comments
0,177,99461681,2016-09-04,78348548,Brenna,"Great place to stay! Definitely a tiny home, b..."
1,177,101460574,2016-09-13,72125554,Rachael,Joe was very friendly and gave us all the info...
2,177,101681475,2016-09-14,21300329,Haley,Amazing property and Joe was a great host! Eve...
3,177,102963808,2016-09-19,53882399,Mike,"Joe was a great host, the description of this ..."
4,177,103447333,2016-09-22,94621370,Carol,He welcomes us when we first arrived and gave ...

In [18]:
# number of reviews per listing
review_counts_per_listing = reviews_gz_df.groupby('listing_id')['id'].nunique()
review_counts_per_listing.head(10)

listing_id
177       39
360       48
590      565
592      147
686      236
1940      34
2086      12
21745    226
31503     55
39405    549
Name: id, dtype: int64

In [19]:
# denver airbnb calendar data
calendar_gz_df = pd.read_csv('calendar.csv.gz', compression='gzip', header=0, sep=',', quotechar='"')
calendar_gz_df.head(10)

,listing_id,date,available,price,adjusted_price,minimum_nights,maximum_nights
0,177,2019-04-27,f,$51.00,$51.00,1,400
1,177,2019-04-28,f,$72.00,$72.00,1,400
2,177,2019-04-29,f,$64.00,$64.00,1,400
3,177,2019-04-30,f,$62.00,$62.00,1,400
4,177,2019-05-01,f,$65.00,$65.00,1,400
5,177,2019-05-02,f,$51.00,$51.00,1,400
6,177,2019-05-03,f,$55.00,$55.00,1,400
7,177,2019-05-04,f,$55.00,$55.00,1,400
8,177,2019-05-05,f,$51.00,$51.00,1,400
9,2466830,2019-04-27,f,$300.00,$300.00,1,1125

In [20]:
# denver airbnb listings data
listings_gz_df = pd.read_csv('listings.csv.gz', compression='gzip', header=0, sep=',', quotechar='"')
listings_gz_df.head()

,id,listing_url,scrape_id,last_scraped,name,summary,space,description,experiences_offered,neighborhood_overview,...,instant_bookable,is_business_travel_ready,cancellation_policy,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,177,https://www.airbnb.com/rooms/177,20190427155417,2019-04-27,Tiny Home in the Heart of the City- ECO FRIENDLY,"160 sq ft + 80 sq ft loft for sleeping, Sleeps...",Here's the fun details of this Tiny Home exper...,"160 sq ft + 80 sq ft loft for sleeping, Sleeps...",none,"Quiet neighborhood next to park, creeks and bi...",...,t,f,strict_14_with_grace_period,f,f,3,3,0,0,1.21
1,360,https://www.airbnb.com/rooms/360,20190427155417,2019-04-27,LoHi Secret garden at the Chickadee Cottage,Come enjoy our oasis is the city and stay at o...,Chickadee Cottage is the largest of our guest ...,Come enjoy our oasis is the city and stay at o...,none,those who are interested in our local brews - ...,...,t,f,moderate,t,t,3,3,0,0,5.58
2,590,https://www.airbnb.com/rooms/590,20190427155417,2019-04-27,Comfortable - and a great value!,"Large guest room in my home, where I also live...",I have been enjoying welcoming many wonderful ...,"Large guest room in my home, where I also live...",none,I love the diversity of my neighborhood and it...,...,f,f,flexible,f,f,2,0,2,0,4.60
3,592,https://www.airbnb.com/rooms/592,20190427155417,2019-04-27,private,This room is in the basement. It does not hav...,This is a basement room. You can sometimes he...,This room is in the basement. It does not hav...,none,NaN,...,f,f,flexible,f,f,2,0,2,0,1.19
4,686,https://www.airbnb.com/rooms/686,20190427155417,2019-04-27,Alexandra's Uptown Queen Bed Room,Thank you for visiting my Queen Bed Room site!...,Thank you for checking out my Bed and Breakfas...,Thank you for visiting my Queen Bed Room site!...,none,"I love my Uptown neighborhood, which is within...",...,t,f,moderate,f,f,2,0,2,0,1.82

In [21]:
# number of unique denver airbnb listings
len(listings_gz_df)

4686

In [27]:
# denver airbnb neighborhoods data
neighbourhoods_df = pd.read_csv('denver_2019_crime.csv')
neighbourhoods_df

,INCIDENT_ID,OFFENSE_ID,OFFENSE_CODE,OFFENSE_CODE_EXTENSION,OFFENSE_TYPE_ID,OFFENSE_CATEGORY_ID,FIRST_OCCURRENCE_DATE,LAST_OCCURRENCE_DATE,REPORTED_DATE,INCIDENT_ADDRESS,GEO_X,GEO_Y,GEO_LON,GEO_LAT,DISTRICT_ID,PRECINCT_ID,NEIGHBORHOOD_ID
0,2.019279e+08,2.020000e+14,1208,0,robbery-residence,robbery,1/12/2019 16:00,1/12/2019 19:00,1/13/2019 14:41,NaN,3171896.0,1694950.0,-104.888750,39.739854,2,223,east-colfax
1,2.019238e+08,2.020000e+14,2404,0,theft-of-motor-vehicle,auto-theft,1/10/2019 18:30,1/11/2019 9:00,1/11/2019 10:06,3300 BLK W 34TH AVE,3131813.0,1703704.0,-105.031119,39.764540,1,113,west-highland
2,2.019260e+08,2.020000e+14,2303,0,theft-shoplift,larceny,1/12/2019 11:30,NaN,1/12/2019 12:01,2341 E COLFAX AVE,3152124.0,1694998.0,-104.959055,39.740330,2,213,city-park
3,2.019600e+10,2.020000e+16,2999,1,criminal-mischief-mtr-veh,public-disorder,1/12/2019 13:40,1/12/2019 13:40,1/12/2019 14:04,13891 E RANDOLPH PL,3189390.0,1716182.0,-104.825985,39.797799,5,521,montbello
4,2.019291e+08,2.020000e+14,3504,0,drug-hallucinogen-possess,drug-alcohol,1/13/2019 22:13,NaN,1/13/2019 23:46,I25 HWYNB / W 6TH AVE FWY,3136312.0,1691440.0,-105.015348,39.730808,1,123,lincoln-park
5,2.019270e+08,2.020000e+14,1315,0,aggravated-assault,aggravated-assault,1/12/2019 20:00,1/12/2019 20:45,1/12/2019 21:19,2299 W ALAMEDA AVE,3136682.0,1684418.0,-105.014166,39.711526,4,411,valverde
6,2.019263e+08,2.020000e+14,5707,0,criminal-trespassing,all-other-crimes,1/12/2019 14:41,NaN,1/12/2019 15:06,1572 N UINTA ST,3170827.0,1695611.0,-104.892536,39.741689,2,223,east-colfax
7,2.019281e+08,2.020000e+14,2404,0,theft-of-motor-vehicle,auto-theft,1/12/2019 9:00,1/12/2019 17:00,1/13/2019 14:09,2000 ELITCH CIR,3137087.0,1698042.0,-105.012467,39.748920,1,123,auraria
8,2.019240e+08,2.020000e+14,2304,0,theft-parts-from-vehicle,theft-from-motor-vehicle,1/11/2019 12:05,NaN,1/11/2019 12:05,4905 N CATHAY ST,3206327.0,1712283.0,-104.765823,39.786736,5,523,gateway-green-valley-ranch
9,2.019244e+08,2.020000e+14,1313,0,assault-simple,other-crimes-against-persons,1/10/2019 22:09,NaN,1/11/2019 15:19,NaN,3130987.0,1688286.0,-105.034338,39.722226,4,411,barnum
10,2.019600e+10,2.020000e+16,2304,0,theft-parts-from-vehicle,theft-from-motor-vehicle,1/11/2019 6:00,1/11/2019 11:00,1/11/2019 12:14,1801 CHESTNUT PL,3140426.0,1700951.0,-105.000535,39.756856,6,612,union-station
11,2.019279e+08,2.020000e+14,2305,0,theft-items-from-vehicle,theft-from-motor-vehicle,1/12/2019 19:20,1/13/2019 2:00,1/13/2019 8:09,2330 N WASHINGTON ST,3146824.0,1699004.0,-104.977819,39.751413,2,211,five-points
12,2.019294e+08,2.020000e+14,5707,0,criminal-trespassing,all-other-crimes,1/14/2019 3:36,NaN,1/14/2019 4:51,1595 N PEARL ST,3146178.0,1695300.0,-104.980192,39.741255,6,621,north-capitol-hill
13,2.019269e+08,2.020000e+14,1315,0,aggravated-assault,aggravated-assault,1/12/2019 20:03,NaN,1/12/2019 21:35,4500 E EVANS AVE,3159059.0,1672320.0,-104.934897,39.677959,3,314,university-hills
14,2.019242e+08,2.020000e+14,2501,0,forgery-checks,white-collar-crime,1/10/2019 8:00,1/11/2019 13:32,1/11/2019 13:32,275 S FEDERAL BLVD,3133517.0,1684400.0,-105.025416,39.711522,4,411,barnum
15,2.019285e+08,2.020000e+14,1315,2,menacing-felony-w-weap,aggravated-assault,1/13/2019 14:55,NaN,1/13/2019 18:18,750 S FEDERAL BLVD,3133728.0,1681289.0,-105.024724,39.702979,4,412,athmar-park
16,2.019258e+08,2.020000e+14,2404,0,theft-of-motor-vehicle,auto-theft,1/12/2019 2:00,1/12/2019 8:35,1/12/2019 9:53,9761 W STANFORD AVE,3110504.0,1656375.0,-105.107645,39.634888,4,423,marston
17,2.019500e+10,2.020000e+16,1102,0,sex-aslt-rape,sexual-assault,1/3/2019 0:00,NaN,1/11/2019 12:14,NaN,NaN,NaN,NaN,NaN,6,612,five-points
18,2.019284e+08,2.020000e+14,2202,0,burglary-residence-by-force,burglary,1/8/2019 12:00,1/13/2019 16:28,1/13/2019 16:28,1135 N OGDEN ST,3147531.0,1692791.0,-104.975433,39.734346,6,623,capitol-hill
19,2.019289e+08,2.020000e+14,2999,1,criminal-mischief-mtr-veh,public-disorder,1/13/2019 19:52,NaN,1/13/2019 20:20,1600 BLK N GROVE ST,3132972.0,1696013.0,-105.027139,39.743410,1,121,west-colfax
20,2.019289e+08,2.020000e+14,4899,0,police-interference,all-other-crimes,1/13/2019 19:20,NaN,1/13/2019 20:56,NaN,3169238.0,1705800.0,-104.897946,39.769688,5,512,stapleton
21,2.019265e+08,2.020000e+14,2399,0,theft-other,larceny,1/10/2019 16:30,NaN,1/12/2019 16:08,1309 N GRANT ST,3145121.0,1693806.0,-104.983981,39.737170,6,623,capitol-hill
22,2.019267e+08,2.020000e+14,2399,1,theft-bicycle,larceny,1/12/2019 17:20,1/12/2019 17:40,1/12/2019 19:20,1155 E 9TH AVE,3147996.0,1691775.0,-104.973800,39.731549,6,623,capitol-hill
23,2.019257e+08,2.020000e+14,5707,0,criminal-trespassing,all-other-crimes,1/12/2019 7:15,NaN,1/12/2019 9:20,NaN,3214984.0,1711933.0,-104.735030,39.785579,5,523,gateway-green-valley-ranch
24,2.019279e+08,2.020000e+14,2605,0,theft-unauth-use-of-ftd,white-collar-crime,1/12/2019 19:20,1/13/2019 2:00,1/13/2019 8:09,2330 N WASHINGTON ST,3146824.0,1699004.0,-104.977819,39.751413,2,211,five-points
25,2.019258e+08,2.020000e+14,2399,0,theft-other,larceny,1/10/2019 14:00,1/10/2019 16:00,1/12/2019 8:21,3675 N JASMINE ST,3163288.0,1705449.0,-104.919120,39.768831,2,221,northeast-park-hill
26,2.019280e+08,2.020000e+14,2399,0,theft-other,larceny,1/13/2019 8:00,1/13/2019 10:10,1/13/2019 10:19,2681 S ACOMA ST,3143844.0,1668637.0,-104.989025,39.668095,3,313,overland
27,2.019288e+08,2.020000e+14,2303,0,theft-shoplift,larceny,1/13/2019 18:50,NaN,1/13/2019 18:50,1385 N KRAMERIA ST,3163958.0,1694247.0,-104.916993,39.738068,2,222,montclair
28,2.019600e+10,2.020000e+16,2305,0,theft-items-from-vehicle,theft-from-motor-vehicle,1/11/2019 12:00,1/12/2019 9:15,1/12/2019 13:24,3025 N NEWTON ST,3130088.0,1702365.0,-105.037279,39.760888,1,113,west-highland
29,2.019262e+08,2.020000e+14,5444,0,traf-habitual-offender,all-other-crimes,1/12/2019 13:51,NaN,1/12/2019 14:15,8200 BLK E COLFAX AVE,3170963.0,1695161.0,-104.892063,39.740451,2,223,east-colfax
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28800,2.019258e+09,2.020000e+15,2803,0,stolen-property-buy-sell-rec,all-other-crimes,4/25/2019 17:40,NaN,4/25/2019 21:22,1055 19TH ST,3143054.0,1698655.0,-104.991234,39.750513,6,611,cbd
28801,2.019268e+09,2.020000e+15,3572,0,drug-methampetamine-possess,drug-alcohol,4/29/2019 22:35,NaN,4/29/2019 22:35,355 S GROVE ST,3133171.0,1683929.0,-105.026655,39.710234,4,412,westwood
28802,2.019249e+09,2.020000e+15,2609,0,fraud-by-use-of-computer,white-collar-crime,3/1/2019 0:00,4/21/2019 20:18,4/21/2019 20:18,14372 E ELK DR,3188716.0,1709536.0,-104.828558,39.779569,5,521,montbello
28803,2.019250e+09,2.020000e+15,2404,0,theft-of-motor-vehicle,auto-theft,4/17/2019 5:00,4/22/2019 8:00,4/22/2019 8:49,1100 BLOCK N INCA ST,3141322.0,1692583.0,-104.997513,39.733871,1,123,lincoln-park
28804,2.019250e+09,2.020000e+15,2399,0,theft-other,larceny,4/19/2019 16:00,4/22/2019 6:30,4/22/2019 9:51,6645 N DUNKIRK ST,3207120.0,1723467.0,-104.762678,39.817419,5,522,dia
28805,2.019251e+09,2.020000e+15,4104,0,liquor-possession,drug-alcohol,4/22/2019 16:45,NaN,4/22/2019 16:59,2000 BLOCK N WASHINGTON ST,3146761.0,1697939.0,-104.978065,39.748490,6,621,five-points
28806,2.019251e+09,2.020000e+15,5016,1,violation-of-court-order,all-other-crimes,4/22/2019 14:33,NaN,4/22/2019 16:08,1905 S UTICA ST,3127916.0,1673645.0,-105.045516,39.682076,4,421,harvey-park
28807,2.019250e+09,2.020000e+15,2308,0,theft-from-bldg,larceny,4/18/2019 23:10,NaN,4/22/2019 8:03,7711 E ACADEMY BLVD,3170098.0,1688065.0,-104.895307,39.720987,3,321,lowry-field
28808,2.019251e+09,2.020000e+15,5707,0,criminal-trespassing,all-other-crimes,4/22/2019 16:51,NaN,4/22/2019 18:21,1653 S COLORADO BLVD,3156983.0,1675619.0,-104.942200,39.687050,3,312,cory-merrill
28809,2.019251e+09,2.020000e+15,2404,0,theft-of-motor-vehicle,auto-theft,4/20/2019 16:30,4/21/2019 7:30,4/22/2019 15:19,2375 E 1ST AVE,3152768.0,1687025.0,-104.956935,39.718432,3,311,cherry-creek
28810,2.019250e+09,2.020000e+15,2404,0,theft-of-motor-vehicle,auto-theft,4/21/2019 17:00,4/22/2019 6:45,4/22/2019 6:45,4982 S ULSTER ST,3170631.0,1653789.0,-104.894224,39.626882,3,324,hampden-south
28811,2.019250e+09,2.020000e+15,2404,0,theft-of-motor-vehicle,auto-theft,4/21/2019 13:00,4/22/2019 5:05,4/22/2019 5:29,2000 BLOCK LARIMER ST,3142853.0,1699693.0,-104.991928,39.753366,6,612,five-points
28812,2.019250e+09,2.020000e+15,2303,0,theft-shoplift,larceny,4/22/2019 7:40,NaN,4/22/2019 8:52,777 N BANNOCK ST,3143312.0,1690483.0,-104.990480,39.728076,1,123,lincoln-park
28813,2.019600e+10,2.020000e+16,2305,0,theft-items-from-vehicle,theft-from-motor-vehicle,4/19/2019 0:00,4/19/2019 8:00,4/23/2019 0:22,700 BLK W 29TH AVE,3141468.0,1701579.0,-104.996817,39.758564,6,612,five-points
28814,2.019252e+09,2.020000e+15,2399,0,theft-other,larceny,4/23/2019 2:26,NaN,4/23/2019 5:42,1300 BLOCK 27TH ST,3144953.0,1701982.0,-104.984414,39.759617,2,211,five-points
28815,2.019600e+10,2.020000e+16,2305,0,theft-items-from-vehicle,theft-from-motor-vehicle,4/18/2019 18:00,4/19/2019 9:20,4/22/2019 13:32,2400 E ASBURY AVE,3152685.0,1673045.0,-104.957527,39.680056,3,314,university-park
28816,2.019600e+10,2.020000e+16,2999,1,criminal-mischief-mtr-veh,public-disorder,4/10/2019 4:00,4/22/2019 16:55,4/22/2019 17:19,3335 S FLAMINGO WAY,3161483.0,1664321.0,-104.926465,39.655958,3,314,university-hills
28817,2.019247e+09,2.020000e+15,4813,0,police-disobey-lawful-order,all-other-crimes,4/20/2019 17:33,NaN,4/20/2019 17:33,NaN,3138452.0,1699255.0,-105.007589,39.752230,1,123,auraria
28818,2.019252e+09,2.020000e+15,5707,0,criminal-trespassing,all-other-crimes,4/22/2019 21:05,NaN,4/22/2019 21:50,1570 E COLFAX AVE,3149411.0,1694762.0,-104.968707,39.739726,6,622,cheesman-park
28819,2.019251e+09,2.020000e+15,2305,0,theft-items-from-vehicle,theft-from-motor-vehicle,4/22/2019 16:55,NaN,4/22/2019 16:57,701 21ST ST,3144469.0,1698541.0,-104.986204,39.750178,6,621,five-points
28820,2.019500e+10,2.020000e+16,1109,0,sex-aslt-non-rape,sexual-assault,11/1/2018 9:00,NaN,2/14/2019 10:59,NaN,NaN,NaN,NaN,NaN,3,322,virginia-village
28821,2.019250e+09,2.020000e+15,2999,1,criminal-mischief-mtr-veh,public-disorder,4/21/2019 23:00,NaN,4/22/2019 8:56,NaN,3130132.0,1679091.0,-105.037544,39.696996,4,412,westwood
28822,2.019600e+10,2.020000e+16,2999,0,criminal-mischief-other,public-disorder,4/21/2019 1:13,4/21/2019 3:30,4/22/2019 7:40,4895 S IRIS ST,3110541.0,1653724.0,-105.107554,39.627610,4,423,marston
28823,2.019251e+09,2.020000e+15,2303,0,theft-shoplift,larceny,4/22/2019 17:25,NaN,4/22/2019 19:17,7800 E SMITH RD,3169238.0,1705800.0,-104.897946,39.769688,5,512,stapleton
28824,2.019250e+09,2.020000e+15,1313,0,assault-simple,other-crimes-against-persons,4/22/2019 10:20,NaN,4/22/2019 13:29,NaN,3214742.0,1713553.0,-104.735843,39.790031,5,523,gateway-green-valley-ranch
28825,2.019250e+09,2.020000e+15,2399,1,theft-bicycle,larceny,4/8/2019 12:00,NaN,4/22/2019 8:30,150 W 9TH AVE,3143499.0,1690969.0,-104.989805,39.729407,6,611,civic-center
28826,2.019251e+09,2.020000e+15,5444,0,traf-habitual-offender,all-other-crimes,4/22/2019 18:50,NaN,4/22/2019 20:33,W ALAMEDA AVE / S YUMA ST,3136582.0,1684291.0,-105.014524,39.711179,4,412,athmar-park
28827,2.019251e+09,2.020000e+15,2303,0,theft-shoplift,larceny,4/22/2019 12:37,4/22/2019 13:00,4/22/2019 15:30,1416 PLATTE ST,3137893.0,1700400.0,-105.009555,39.755381,1,113,highland
28828,2.019251e+09,2.020000e+15,4899,0,police-interference,all-other-crimes,4/22/2019 19:47,NaN,4/22/2019 21:41,E 44TH AVE / N MILWAUKEE ST,3154045.0,1708607.0,-104.951933,39.777657,2,212,elyria-swansea
28829,2.019208e+09,2.020000e+15,2999,1,criminal-mischief-mtr-veh,public-disorder,4/2/2019 17:30,NaN,4/3/2019 21:43,I70 HWYWB / N CENTRAL PARK BLVD,3173428.0,1708597.0,-104.882973,39.777289,5,511,stapleton

In [28]:
# number of denver neighborhoods in airbnb data
len(neighbourhoods_df)

28830

In [29]:
crime_df = pd.read_csv('denver_2019_crime.csv')
crime_df.head()

,INCIDENT_ID,OFFENSE_ID,OFFENSE_CODE,OFFENSE_CODE_EXTENSION,OFFENSE_TYPE_ID,OFFENSE_CATEGORY_ID,FIRST_OCCURRENCE_DATE,LAST_OCCURRENCE_DATE,REPORTED_DATE,INCIDENT_ADDRESS,GEO_X,GEO_Y,GEO_LON,GEO_LAT,DISTRICT_ID,PRECINCT_ID,NEIGHBORHOOD_ID
0,2.019279e+08,2.020000e+14,1208,0,robbery-residence,robbery,1/12/2019 16:00,1/12/2019 19:00,1/13/2019 14:41,NaN,3171896.0,1694950.0,-104.888750,39.739854,2,223,east-colfax
1,2.019238e+08,2.020000e+14,2404,0,theft-of-motor-vehicle,auto-theft,1/10/2019 18:30,1/11/2019 9:00,1/11/2019 10:06,3300 BLK W 34TH AVE,3131813.0,1703704.0,-105.031119,39.764540,1,113,west-highland
2,2.019260e+08,2.020000e+14,2303,0,theft-shoplift,larceny,1/12/2019 11:30,NaN,1/12/2019 12:01,2341 E COLFAX AVE,3152124.0,1694998.0,-104.959055,39.740330,2,213,city-park
3,2.019600e+10,2.020000e+16,2999,1,criminal-mischief-mtr-veh,public-disorder,1/12/2019 13:40,1/12/2019 13:40,1/12/2019 14:04,13891 E RANDOLPH PL,3189390.0,1716182.0,-104.825985,39.797799,5,521,montbello
4,2.019291e+08,2.020000e+14,3504,0,drug-hallucinogen-possess,drug-alcohol,1/13/2019 22:13,NaN,1/13/2019 23:46,I25 HWYNB / W 6TH AVE FWY,3136312.0,1691440.0,-105.015348,39.730808,1,123,lincoln-park

In [30]:
crime_1_df = crime_df[crime_df.OFFENSE_CATEGORY_ID != 'traffic-accident']
crime_1_df.head()

,INCIDENT_ID,OFFENSE_ID,OFFENSE_CODE,OFFENSE_CODE_EXTENSION,OFFENSE_TYPE_ID,OFFENSE_CATEGORY_ID,FIRST_OCCURRENCE_DATE,LAST_OCCURRENCE_DATE,REPORTED_DATE,INCIDENT_ADDRESS,GEO_X,GEO_Y,GEO_LON,GEO_LAT,DISTRICT_ID,PRECINCT_ID,NEIGHBORHOOD_ID
0,2.019279e+08,2.020000e+14,1208,0,robbery-residence,robbery,1/12/2019 16:00,1/12/2019 19:00,1/13/2019 14:41,NaN,3171896.0,1694950.0,-104.888750,39.739854,2,223,east-colfax
1,2.019238e+08,2.020000e+14,2404,0,theft-of-motor-vehicle,auto-theft,1/10/2019 18:30,1/11/2019 9:00,1/11/2019 10:06,3300 BLK W 34TH AVE,3131813.0,1703704.0,-105.031119,39.764540,1,113,west-highland
2,2.019260e+08,2.020000e+14,2303,0,theft-shoplift,larceny,1/12/2019 11:30,NaN,1/12/2019 12:01,2341 E COLFAX AVE,3152124.0,1694998.0,-104.959055,39.740330,2,213,city-park
3,2.019600e+10,2.020000e+16,2999,1,criminal-mischief-mtr-veh,public-disorder,1/12/2019 13:40,1/12/2019 13:40,1/12/2019 14:04,13891 E RANDOLPH PL,3189390.0,1716182.0,-104.825985,39.797799,5,521,montbello
4,2.019291e+08,2.020000e+14,3504,0,drug-hallucinogen-possess,drug-alcohol,1/13/2019 22:13,NaN,1/13/2019 23:46,I25 HWYNB / W 6TH AVE FWY,3136312.0,1691440.0,-105.015348,39.730808,1,123,lincoln-park

In [31]:
pd.write_csv()

AttributeError: module 'pandas' has no attribute 'write_csv'

In [32]:
# denver crime data cleaned up by filtering columns
crime_2_df = crime_df[['INCIDENT_ID', 'OFFENSE_ID', 'OFFENSE_CODE', 'OFFENSE_TYPE_ID', 'OFFENSE_CATEGORY_ID', 'REPORTED_DATE', 'GEO_LON', 'GEO_LAT', 'NEIGHBORHOOD_ID']]
crime_2_df.head()

,INCIDENT_ID,OFFENSE_ID,OFFENSE_CODE,OFFENSE_TYPE_ID,OFFENSE_CATEGORY_ID,REPORTED_DATE,GEO_LON,GEO_LAT,NEIGHBORHOOD_ID
0,2.019279e+08,2.020000e+14,1208,robbery-residence,robbery,1/13/2019 14:41,-104.888750,39.739854,east-colfax
1,2.019238e+08,2.020000e+14,2404,theft-of-motor-vehicle,auto-theft,1/11/2019 10:06,-105.031119,39.764540,west-highland
2,2.019260e+08,2.020000e+14,2303,theft-shoplift,larceny,1/12/2019 12:01,-104.959055,39.740330,city-park
3,2.019600e+10,2.020000e+16,2999,criminal-mischief-mtr-veh,public-disorder,1/12/2019 14:04,-104.825985,39.797799,montbello
4,2.019291e+08,2.020000e+14,3504,drug-hallucinogen-possess,drug-alcohol,1/13/2019 23:46,-105.015348,39.730808,lincoln-park

In [33]:
# number of crimes in denver per category (not sure difference between incident id and offense id)
crimes_by_category_df = crime_2_df.groupby('OFFENSE_CATEGORY_ID')[['INCIDENT_ID', 'OFFENSE_ID']].nunique()
crimes_by_category_df

                              INCIDENT_ID  OFFENSE_ID
OFFENSE_CATEGORY_ID
aggravated-assault                   1062           5
all-other-crimes                     4805           7
arson                                  47           4
auto-theft                           2583           5
burglary                             1688           5
drug-alcohol                         2387           5
larceny                              4471           5
murder                                 27           3
other-crimes-against-persons         2197           6
public-disorder                      3711           6
robbery                               530           5
sexual-assault                        400           4
theft-from-motor-vehicle             3721           5
white-collar-crime                    621           4

In [34]:
# number of crimes per neighborhood (sorted least reported crime to most)
crimes_by_neighborhood_df = crime_2_df.groupby('NEIGHBORHOOD_ID')[['INCIDENT_ID', 'OFFENSE_ID']].nunique()
crimes_by_neighborhood_df.sort_values('OFFENSE_ID').head()

                 INCIDENT_ID  OFFENSE_ID
NEIGHBORHOOD_ID
wellshire                 28           3
city-park                174           3
barnum-west              180           3
country-club              51           3
jefferson-park           215           4

In [36]:
print(crimes_by_neighborhood_df)

                            INCIDENT_ID  OFFENSE_ID
NEIGHBORHOOD_ID
athmar-park                         295           5
auraria                             226           4
baker                               440           4
barnum                              240           6
barnum-west                         180           3
bear-valley                         200           4
belcaro                             125           4
berkeley                            228           5
capitol-hill                        991           4
cbd                                1103           5
chaffee-park                        130           5
cheesman-park                       453           5
cherry-creek                        330           4
city-park                           174           3
city-park-west                      387           4
civic-center                        799           5
clayton                             216           5
cole                                197           4
college-view-south-platte           367           4
congress-park                       212           5
cory-merrill                        128           4
country-club                         51           3
dia                                 604           4
east-colfax                         640           6
elyria-swansea                      317           5
five-points                        1758           5
fort-logan                          176           4
gateway-green-valley-ranch          726           5
globeville                          331           4
goldsmith                           246           4
...                                 ...         ...
northeast-park-hill                 470           5
overland                            228           4
platt-park                          159           4
regis                               159           4
rosedale                             78           5
ruby-hill                           282           4
skyland                              73           4
sloan-lake                          196           4
south-park-hill                     156           4
southmoor-park                      120           4
speer                               366           5
stapleton                          1197           4
sun-valley                          178           4
sunnyside                           294           4
union-station                       884           5
university                          166           4
university-hills                    231           5
university-park                     197           4
valverde                            183           4
villa-park                          339           5
virginia-village                    302           5
washington-park                     114           4
washington-park-west                139           4
washington-virginia-vale            386           4
wellshire                            28           3
west-colfax                         580           5
west-highland                       248           4
westwood                            496           5
whittier                            170           5
windsor                             249           4

[78 rows x 2 columns]

In [35]:
# number of crimes per neighborhood (viewing 5 neighborhoods with highest numbers of reported crimes)
crimes_by_neighborhood_df.sort_values('OFFENSE_ID').tail()

                   INCIDENT_ID  OFFENSE_ID
NEIGHBORHOOD_ID
athmar-park                295           5
montbello                  914           6
east-colfax                640           6
barnum                     240           6
harvey-park-south          219           6