In [2]:
import pandas as pd

# denver airbnb review data
reviews_gz_df = pd.read_csv('reviews.csv.gz', compression='gzip', header=0, sep=',', quotechar='"')
reviews_gz_df.head()

,listing_id,id,date,reviewer_id,reviewer_name,comments
0,177,99461681,2016-09-04,78348548,Brenna,"Great place to stay! Definitely a tiny home, b..."
1,177,101460574,2016-09-13,72125554,Rachael,Joe was very friendly and gave us all the info...
2,177,101681475,2016-09-14,21300329,Haley,Amazing property and Joe was a great host! Eve...
3,177,102963808,2016-09-19,53882399,Mike,"Joe was a great host, the description of this ..."
4,177,103447333,2016-09-22,94621370,Carol,He welcomes us when we first arrived and gave ...

In [3]:
# number of reviews per listing
review_counts_per_listing = reviews_gz_df.groupby('listing_id')['id'].nunique()
review_counts_per_listing.head(10)

listing_id
177       39
360       48
590      565
592      147
686      236
1940      34
2086      12
21745    226
31503     55
39405    549
Name: id, dtype: int64

In [4]:
# denver airbnb calendar data
calendar_gz_df = pd.read_csv('calendar.csv.gz', compression='gzip', header=0, sep=',', quotechar='"')
calendar_gz_df.head(10)

,listing_id,date,available,price,adjusted_price,minimum_nights,maximum_nights
0,177,2019-04-27,f,$51.00,$51.00,1,400
1,177,2019-04-28,f,$72.00,$72.00,1,400
2,177,2019-04-29,f,$64.00,$64.00,1,400
3,177,2019-04-30,f,$62.00,$62.00,1,400
4,177,2019-05-01,f,$65.00,$65.00,1,400
5,177,2019-05-02,f,$51.00,$51.00,1,400
6,177,2019-05-03,f,$55.00,$55.00,1,400
7,177,2019-05-04,f,$55.00,$55.00,1,400
8,177,2019-05-05,f,$51.00,$51.00,1,400
9,2466830,2019-04-27,f,$300.00,$300.00,1,1125

In [5]:
# denver airbnb listings data
listings_gz_df = pd.read_csv('listings.csv.gz', compression='gzip', header=0, sep=',', quotechar='"')
listings_gz_df.head()

,id,listing_url,scrape_id,last_scraped,name,summary,space,description,experiences_offered,neighborhood_overview,...,instant_bookable,is_business_travel_ready,cancellation_policy,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,177,https://www.airbnb.com/rooms/177,20190427155417,2019-04-27,Tiny Home in the Heart of the City- ECO FRIENDLY,"160 sq ft + 80 sq ft loft for sleeping, Sleeps...",Here's the fun details of this Tiny Home exper...,"160 sq ft + 80 sq ft loft for sleeping, Sleeps...",none,"Quiet neighborhood next to park, creeks and bi...",...,t,f,strict_14_with_grace_period,f,f,3,3,0,0,1.21
1,360,https://www.airbnb.com/rooms/360,20190427155417,2019-04-27,LoHi Secret garden at the Chickadee Cottage,Come enjoy our oasis is the city and stay at o...,Chickadee Cottage is the largest of our guest ...,Come enjoy our oasis is the city and stay at o...,none,those who are interested in our local brews - ...,...,t,f,moderate,t,t,3,3,0,0,5.58
2,590,https://www.airbnb.com/rooms/590,20190427155417,2019-04-27,Comfortable - and a great value!,"Large guest room in my home, where I also live...",I have been enjoying welcoming many wonderful ...,"Large guest room in my home, where I also live...",none,I love the diversity of my neighborhood and it...,...,f,f,flexible,f,f,2,0,2,0,4.60
3,592,https://www.airbnb.com/rooms/592,20190427155417,2019-04-27,private,This room is in the basement. It does not hav...,This is a basement room. You can sometimes he...,This room is in the basement. It does not hav...,none,NaN,...,f,f,flexible,f,f,2,0,2,0,1.19
4,686,https://www.airbnb.com/rooms/686,20190427155417,2019-04-27,Alexandra's Uptown Queen Bed Room,Thank you for visiting my Queen Bed Room site!...,Thank you for checking out my Bed and Breakfas...,Thank you for visiting my Queen Bed Room site!...,none,"I love my Uptown neighborhood, which is within...",...,t,f,moderate,f,f,2,0,2,0,1.82

In [6]:
# number of unique denver airbnb listings
len(listings_gz_df)

4686

In [7]:
# denver airbnb neighborhoods data
neighbourhoods_df = pd.read_csv('neighbourhoods.csv')
neighbourhoods_df.head()

   neighbourhood_group neighbourhood
0                  NaN   Athmar Park
1                  NaN       Auraria
2                  NaN         Baker
3                  NaN        Barnum
4                  NaN   Barnum West

In [8]:
# number of denver neighborhoods in airbnb data
len(neighbourhoods_df)

78

In [9]:
crime_df = pd.read_csv('denver_2019_crime.csv')
crime_df.head()

,INCIDENT_ID,OFFENSE_ID,OFFENSE_CODE,OFFENSE_CODE_EXTENSION,OFFENSE_TYPE_ID,OFFENSE_CATEGORY_ID,FIRST_OCCURRENCE_DATE,LAST_OCCURRENCE_DATE,REPORTED_DATE,INCIDENT_ADDRESS,GEO_X,GEO_Y,GEO_LON,GEO_LAT,DISTRICT_ID,PRECINCT_ID,NEIGHBORHOOD_ID
0,2.019279e+08,2.020000e+14,1208,0,robbery-residence,robbery,1/12/2019 16:00,1/12/2019 19:00,1/13/2019 14:41,NaN,3171896.0,1694950.0,-104.888750,39.739854,2,223,east-colfax
1,2.019238e+08,2.020000e+14,2404,0,theft-of-motor-vehicle,auto-theft,1/10/2019 18:30,1/11/2019 9:00,1/11/2019 10:06,3300 BLK W 34TH AVE,3131813.0,1703704.0,-105.031119,39.764540,1,113,west-highland
2,2.019260e+08,2.020000e+14,2303,0,theft-shoplift,larceny,1/12/2019 11:30,NaN,1/12/2019 12:01,2341 E COLFAX AVE,3152124.0,1694998.0,-104.959055,39.740330,2,213,city-park
3,2.019600e+10,2.020000e+16,2999,1,criminal-mischief-mtr-veh,public-disorder,1/12/2019 13:40,1/12/2019 13:40,1/12/2019 14:04,13891 E RANDOLPH PL,3189390.0,1716182.0,-104.825985,39.797799,5,521,montbello
4,2.019291e+08,2.020000e+14,3504,0,drug-hallucinogen-possess,drug-alcohol,1/13/2019 22:13,NaN,1/13/2019 23:46,I25 HWYNB / W 6TH AVE FWY,3136312.0,1691440.0,-105.015348,39.730808,1,123,lincoln-park

In [10]:
crime_1_df = crime_df[crime_df.OFFENSE_CATEGORY_ID != 'traffic-accident']
crime_1_df.head()

,INCIDENT_ID,OFFENSE_ID,OFFENSE_CODE,OFFENSE_CODE_EXTENSION,OFFENSE_TYPE_ID,OFFENSE_CATEGORY_ID,FIRST_OCCURRENCE_DATE,LAST_OCCURRENCE_DATE,REPORTED_DATE,INCIDENT_ADDRESS,GEO_X,GEO_Y,GEO_LON,GEO_LAT,DISTRICT_ID,PRECINCT_ID,NEIGHBORHOOD_ID
0,2.019279e+08,2.020000e+14,1208,0,robbery-residence,robbery,1/12/2019 16:00,1/12/2019 19:00,1/13/2019 14:41,NaN,3171896.0,1694950.0,-104.888750,39.739854,2,223,east-colfax
1,2.019238e+08,2.020000e+14,2404,0,theft-of-motor-vehicle,auto-theft,1/10/2019 18:30,1/11/2019 9:00,1/11/2019 10:06,3300 BLK W 34TH AVE,3131813.0,1703704.0,-105.031119,39.764540,1,113,west-highland
2,2.019260e+08,2.020000e+14,2303,0,theft-shoplift,larceny,1/12/2019 11:30,NaN,1/12/2019 12:01,2341 E COLFAX AVE,3152124.0,1694998.0,-104.959055,39.740330,2,213,city-park
3,2.019600e+10,2.020000e+16,2999,1,criminal-mischief-mtr-veh,public-disorder,1/12/2019 13:40,1/12/2019 13:40,1/12/2019 14:04,13891 E RANDOLPH PL,3189390.0,1716182.0,-104.825985,39.797799,5,521,montbello
4,2.019291e+08,2.020000e+14,3504,0,drug-hallucinogen-possess,drug-alcohol,1/13/2019 22:13,NaN,1/13/2019 23:46,I25 HWYNB / W 6TH AVE FWY,3136312.0,1691440.0,-105.015348,39.730808,1,123,lincoln-park

In [11]:
# denver crime data cleaned up by filtering columns
crime_2_df = crime_df[['INCIDENT_ID', 'OFFENSE_ID', 'OFFENSE_CODE', 'OFFENSE_TYPE_ID', 'OFFENSE_CATEGORY_ID', 'REPORTED_DATE', 'GEO_LON', 'GEO_LAT', 'NEIGHBORHOOD_ID']]
crime_2_df.head()

,INCIDENT_ID,OFFENSE_ID,OFFENSE_CODE,OFFENSE_TYPE_ID,OFFENSE_CATEGORY_ID,REPORTED_DATE,GEO_LON,GEO_LAT,NEIGHBORHOOD_ID
0,2.019279e+08,2.020000e+14,1208,robbery-residence,robbery,1/13/2019 14:41,-104.888750,39.739854,east-colfax
1,2.019238e+08,2.020000e+14,2404,theft-of-motor-vehicle,auto-theft,1/11/2019 10:06,-105.031119,39.764540,west-highland
2,2.019260e+08,2.020000e+14,2303,theft-shoplift,larceny,1/12/2019 12:01,-104.959055,39.740330,city-park
3,2.019600e+10,2.020000e+16,2999,criminal-mischief-mtr-veh,public-disorder,1/12/2019 14:04,-104.825985,39.797799,montbello
4,2.019291e+08,2.020000e+14,3504,drug-hallucinogen-possess,drug-alcohol,1/13/2019 23:46,-105.015348,39.730808,lincoln-park

In [12]:
# number of crimes in denver per category (not sure difference between incident id and offense id)
crimes_by_category_df = crime_2_df.groupby('OFFENSE_CATEGORY_ID')[['INCIDENT_ID', 'OFFENSE_ID']].nunique()
crimes_by_category_df

                              INCIDENT_ID  OFFENSE_ID
OFFENSE_CATEGORY_ID
aggravated-assault                   1062           5
all-other-crimes                     4805           7
arson                                  47           4
auto-theft                           2583           5
burglary                             1688           5
drug-alcohol                         2387           5
larceny                              4471           5
murder                                 27           3
other-crimes-against-persons         2197           6
public-disorder                      3711           6
robbery                               530           5
sexual-assault                        400           4
theft-from-motor-vehicle             3721           5
white-collar-crime                    621           4

In [13]:
# number of crimes per neighborhood (sorted least reported crime to most)
crimes_by_neighborhood_df = crime_2_df.groupby('NEIGHBORHOOD_ID')[['INCIDENT_ID', 'OFFENSE_ID']].nunique()
crimes_by_neighborhood_df.sort_values('OFFENSE_ID').head()

                 INCIDENT_ID  OFFENSE_ID
NEIGHBORHOOD_ID
wellshire                 28           3
city-park                174           3
barnum-west              180           3
country-club              51           3
jefferson-park           215           4

In [14]:
# number of crimes per neighborhood (viewing 5 neighborhoods with highest numbers of reported crimes)
crimes_by_neighborhood_df.sort_values('OFFENSE_ID').tail()

                   INCIDENT_ID  OFFENSE_ID
NEIGHBORHOOD_ID
athmar-park                295           5
montbello                  914           6
east-colfax                640           6
barnum                     240           6
harvey-park-south          219           6

In [15]:
pd.set_option('display.max_columns', None)
listings_gz_df = pd.read_csv('listings.csv.gz', compression = 'gzip', header = 0, sep = ',', quotechar = '"')
listings_gz_df.neighbourhood = listings_gz_df.neighbourhood.str.lower()
listings_gz_df.neighbourhood_cleansed = listings_gz_df.neighbourhood_cleansed.str.lower()
listings_gz_df.host_neighbourhood = listings_gz_df.host_neighbourhood.str.lower()
listings_gz_df.head()

,id,listing_url,scrape_id,last_scraped,name,summary,space,description,experiences_offered,neighborhood_overview,notes,transit,access,interaction,house_rules,thumbnail_url,medium_url,picture_url,xl_picture_url,host_id,host_url,host_name,host_since,host_location,host_about,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_thumbnail_url,host_picture_url,host_neighbourhood,host_listings_count,host_total_listings_count,host_verifications,host_has_profile_pic,host_identity_verified,street,neighbourhood,neighbourhood_cleansed,neighbourhood_group_cleansed,city,state,zipcode,market,smart_location,country_code,country,latitude,longitude,is_location_exact,property_type,room_type,accommodates,bathrooms,bedrooms,beds,bed_type,amenities,square_feet,price,weekly_price,monthly_price,security_deposit,cleaning_fee,guests_included,extra_people,minimum_nights,maximum_nights,minimum_minimum_nights,maximum_minimum_nights,minimum_maximum_nights,maximum_maximum_nights,minimum_nights_avg_ntm,maximum_nights_avg_ntm,calendar_updated,has_availability,availability_30,availability_60,availability_90,availability_365,calendar_last_scraped,number_of_reviews,number_of_reviews_ltm,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,requires_license,license,jurisdiction_names,instant_bookable,is_business_travel_ready,cancellation_policy,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,177,https://www.airbnb.com/rooms/177,20190427155417,2019-04-27,Tiny Home in the Heart of the City- ECO FRIENDLY,"160 sq ft + 80 sq ft loft for sleeping, Sleeps...",Here's the fun details of this Tiny Home exper...,"160 sq ft + 80 sq ft loft for sleeping, Sleeps...",none,"Quiet neighborhood next to park, creeks and bi...",STR Business File (In Photo Section) Lodger's ...,"Car is best, but public transportation is with...",The entire Tiny Home and shared back yard. Plu...,The Tiny Home is setup as self check-in. I'm a...,Please leave the east and west windows open a ...,NaN,NaN,https://a0.muscache.com/im/pictures/a1745ab2-b...,NaN,615,https://www.airbnb.com/users/show/615,Joe,2008-07-07,"Denver, Colorado, United States","I'm originally from Oklahoma, but have lived i...",within an hour,100%,NaN,t,https://a0.muscache.com/im/pictures/user/905d6...,https://a0.muscache.com/im/pictures/user/905d6...,virginia village,3.0,3.0,"['email', 'phone', 'google', 'reviews', 'kba']",t,t,"Denver, CO, United States",virginia village,virginia village,NaN,Denver,CO,80246.0,Denver,"Denver, CO",US,United States,39.69585,-104.92582,t,Guesthouse,Entire home/apt,2,1.0,1.0,1.0,Real Bed,"{TV,Wifi,""Air conditioning"",Kitchen,""Free park...",NaN,$56.00,NaN,NaN,"$1,500.00",$50.00,1,$15.00,1,400,1,1,400,400,1.0,400.0,today,t,0,0,0,0,2019-04-27,39,1,2016-09-04,2019-03-24,94.0,10.0,10.0,10.0,10.0,9.0,9.0,t,STR-2016-BFN-0004968,"{""Colorado State"","" the City and County of Den...",t,f,strict_14_with_grace_period,f,f,3,3,0,0,1.21
1,360,https://www.airbnb.com/rooms/360,20190427155417,2019-04-27,LoHi Secret garden at the Chickadee Cottage,Come enjoy our oasis is the city and stay at o...,Chickadee Cottage is the largest of our guest ...,Come enjoy our oasis is the city and stay at o...,none,those who are interested in our local brews - ...,WIFI: Once you have arrived you can find the...,there are several bus lines that cross the nei...,"Chickadee is the main the main property, sever...",We live on the property in the green house dir...,NUMBER ONE HOUSE RULE: please let us know ASAP...,NaN,NaN,https://a0.muscache.com/im/pictures/f622ba3c-c...,NaN,666,https://www.airbnb.com/users/show/666,Jennifer & Giovanni,2008-07-08,"Denver, Colorado, United States",We are a community of artists and tinkerers.\r...,within an hour,100%,NaN,t,https://a0.muscache.com/im/users/666/profile_p...,https://a0.muscache.com/im/users/666/profile_p...,highland,3.0,3.0,"['email', 'phone', 'facebook', 'reviews', 'jum...",t,t,"Denver, CO, United States",highland,highland,NaN,Denver,CO,80211.0,Denver,"Denver, CO",US,United States,39.76703,-105.00256,t,Guesthouse,Entire home/apt,5,1.0,2.0,2.0,Futon,"{TV,Wifi,""Air conditioning"",Kitchen,""Free stre...",NaN,$140.00,NaN,NaN,$150.00,$40.00,2,$15.00,1,29,1,2,29,29,1.1,29.0,3 days ago,t,10,20,34,290,2019-04-27,48,48,2018-08-13,2019-03-29,100.0,10.0,10.0,10.0,10.0,10.0,10.0,t,2017-BFN-0002177,"{""Colorado State"","" the City and County of Den...",t,f,moderate,t,t,3,3,0,0,5.58
2,590,https://www.airbnb.com/rooms/590,20190427155417,2019-04-27,Comfortable - and a great value!,"Large guest room in my home, where I also live...",I have been enjoying welcoming many wonderful ...,"Large guest room in my home, where I also live...",none,I love the diversity of my neighborhood and it...,Denver (and Colorado) now impose lodging tax o...,The number 20 RTD bus is 2 blocks away to go d...,You may make yourselves at home in all public ...,I am happy to interact as much or as little as...,NaN,NaN,NaN,https://a0.muscache.com/im/pictures/110931/309...,NaN,933,https://www.airbnb.com/users/show/933,Jill,2008-07-21,"Denver, Colorado, United States",I am friendly and I love meeting people from a...,within an hour,100%,NaN,t,https://a0.muscache.com/im/users/933/profile_p...,https://a0.muscache.com/im/users/933/profile_p...,north park hill,2.0,2.0,"['email', 'phone', 'facebook', 'reviews', 'jum...",t,t,"Denver, CO, United States",north park hill,north park hill,NaN,Denver,CO,80207.0,Denver,"Denver, CO",US,United States,39.75361,-104.91237,t,House,Private room,3,1.0,1.0,1.0,Real Bed,"{Internet,Wifi,""Air conditioning"",Kitchen,""Fre...",NaN,$61.00,$375.00,"$1,275.00",NaN,$10.00,1,$5.00,1,300,1,1,300,300,1.0,300.0,4 weeks ago,t,0,3,7,93,2019-04-27,565,40,2009-03-29,2019-03-27,97.0,10.0,10.0,10.0,10.0,10.0,10.0,t,2018-BFN-O0O5791,"{""Colorado State"","" the City and County of Den...",f,f,flexible,f,f,2,0,2,0,4.60
3,592,https://www.airbnb.com/rooms/592,20190427155417,2019-04-27,private,This room is in the basement. It does not hav...,This is a basement room. You can sometimes he...,This room is in the basement. It does not hav...,none,NaN,Denver (and Colorado) now impose lodging tax o...,It's convenient and easy to get here from the ...,Access to all public parts of the house - kitc...,I'm happy to interact with you if you wish. O...,No smoking in or near the house. I prefer n...,NaN,NaN,https://a0.muscache.com/im/pictures/110942/171...,NaN,933,https://www.airbnb.com/users/show/933,Jill,2008-07-21,"Denver, Colorado, United States",I am friendly and I love meeting people from a...,within an hour,100%,NaN,t,https://a0.muscache.com/im/users/933/profile_p...,https://a0.muscache.com/im/users/933/profile_p...,north park hill,2.0,2.0,"['email', 'phone', 'facebook', 'reviews', 'jum...",t,t,"Denver, CO, United States",north park hill,north park hill,NaN,Denver,CO,80207.0,Denver,"Denver, CO",US,United States,39.75438,-104.91156,t,House,Private room,2,1.0,1.0,1.0,Real Bed,"{Internet,Wifi,""Air conditioning"",Kitchen,""Fre...",NaN,$42.00,$295.00,$975.00,NaN,$10.00,1,$5.00,30,365,30,30,365,365,30.0,365.0,6 months ago,t,15,15,15,94,2019-04-27,147,5,2009-02-21,2019-03-22,97.0,9.0,9.0,10.0,10.0,10.0,10.0,t,2018-BFN-O0O5791,"{""Colorado State"","" the City and County of Den...",f,f,flexible,f,f,2,0,2,0,1.19
4,686,https://www.airbnb.com/rooms/686,20190427155417,2019-04-27,Alexandra's Uptown Queen Bed Room,Thank you for visiting my Queen Bed Room site!...,Thank you for checking out my Bed and Breakfas...,Thank you for visiting my Queen Bed Room site!...,none,"I love my Uptown neighborhood, which is within...",My STR license with the City and County of Den...,Getting around Denver is easy from here withou...,"Living room, dining room, kitchen, refrigerato...",I generally have a great deal of interaction w...,No smoking or vaping. No pets. If kitchen is u...,NaN,NaN,https://a0.muscache.com/im/pictures/108112/e6d...,NaN,990,https://www.airbnb.com/users/show/990,Alexandra,2008-07-23,"Denver, Colorado, United States","Denver native, former teacher, musician, chapl...",within an hour,100%,NaN,f,https://a0.muscache.com/im/pictures/c7c053dd-d...,https://a0.muscache.com/im/pictures/c7c053dd-d...,north capitol hill,2.0,2.0,"['email', 'phone', 'reviews', 'kba']",t,t,"Denver, CO, United States",north capitol hill,north capitol hill,NaN,Denver,CO,80203.0,Denver,"Denver, CO",US,United States,39.74503,-104.97756,t,House,Private room,2,2.0,1.0,1.0,Real Bed,"{TV,""Cable TV"",Internet,Wifi,""Air conditioning...",NaN,$70.00,NaN,"$1,470.00",$0.00,$10.00,1,$0.00,2,180,2,2,180,180,2.0,180.0,2 days ago,t,19,49,69,344,2019-04-27,236,13,2008-08-28,2019-04-16,95.0,10.0,10.0,10.0,10.0,10.0,10.0,t,2016-BFN-0008368,"{""Colorado State"","" the City and County of Den...",t,f,moderate,f,f,2,0,2,0,1.82

In [16]:
list(listings_gz_df)

['id',
 'listing_url',
 'scrape_id',
 'last_scraped',
 'name',
 'summary',
 'space',
 'description',
 'experiences_offered',
 'neighborhood_overview',
 'notes',
 'transit',
 'access',
 'interaction',
 'house_rules',
 'thumbnail_url',
 'medium_url',
 'picture_url',
 'xl_picture_url',
 'host_id',
 'host_url',
 'host_name',
 'host_since',
 'host_location',
 'host_about',
 'host_response_time',
 'host_response_rate',
 'host_acceptance_rate',
 'host_is_superhost',
 'host_thumbnail_url',
 'host_picture_url',
 'host_neighbourhood',
 'host_listings_count',
 'host_total_listings_count',
 'host_verifications',
 'host_has_profile_pic',
 'host_identity_verified',
 'street',
 'neighbourhood',
 'neighbourhood_cleansed',
 'neighbourhood_group_cleansed',
 'city',
 'state',
 'zipcode',
 'market',
 'smart_location',
 'country_code',
 'country',
 'latitude',
 'longitude',
 'is_location_exact',
 'property_type',
 'room_type',
 'accommodates',
 'bathrooms',
 'bedrooms',
 'beds',
 'bed_type',
 'amenities',
 'square_feet',
 'price',
 'weekly_price',
 'monthly_price',
 'security_deposit',
 'cleaning_fee',
 'guests_included',
 'extra_people',
 'minimum_nights',
 'maximum_nights',
 'minimum_minimum_nights',
 'maximum_minimum_nights',
 'minimum_maximum_nights',
 'maximum_maximum_nights',
 'minimum_nights_avg_ntm',
 'maximum_nights_avg_ntm',
 'calendar_updated',
 'has_availability',
 'availability_30',
 'availability_60',
 'availability_90',
 'availability_365',
 'calendar_last_scraped',
 'number_of_reviews',
 'number_of_reviews_ltm',
 'first_review',
 'last_review',
 'review_scores_rating',
 'review_scores_accuracy',
 'review_scores_cleanliness',
 'review_scores_checkin',
 'review_scores_communication',
 'review_scores_location',
 'review_scores_value',
 'requires_license',
 'license',
 'jurisdiction_names',
 'instant_bookable',
 'is_business_travel_ready',
 'cancellation_policy',
 'require_guest_profile_picture',
 'require_guest_phone_verification',
 'calculated_host_listings_count',
 'calculated_host_listings_count_entire_homes',
 'calculated_host_listings_count_private_rooms',
 'calculated_host_listings_count_shared_rooms',
 'reviews_per_month']

In [17]:
listings_df = pd.read_csv('listings.csv')
listings_df.neighbourhood = listings_df.neighbourhood.str.lower()
listings_df.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,177,Tiny Home in the Heart of the City- ECO FRIENDLY,615,Joe,NaN,virginia village,39.69585,-104.92582,Entire home/apt,56,1,39,2019-03-24,1.21,3,0
1,360,LoHi Secret garden at the Chickadee Cottage,666,Jennifer & Giovanni,NaN,highland,39.76703,-105.00256,Entire home/apt,140,1,48,2019-03-29,5.58,3,290
2,590,Comfortable - and a great value!,933,Jill,NaN,north park hill,39.75361,-104.91237,Private room,61,1,565,2019-03-27,4.60,2,93
3,592,private,933,Jill,NaN,north park hill,39.75438,-104.91156,Private room,42,30,147,2019-03-22,1.19,2,94
4,686,Alexandra's Uptown Queen Bed Room,990,Alexandra,NaN,north capitol hill,39.74503,-104.97756,Private room,70,2,236,2019-04-16,1.82,2,344

In [18]:
denver_2019_crime_df = pd.read_csv('denver_2019_crime.csv')

In [19]:
denver_2019_crime_df = denver_2019_crime_df[denver_2019_crime_df.OFFENSE_CATEGORY_ID != 'traffic-accident']

In [20]:
# denver crime data cleaned up by filtering columns
crime_2_df = crime_df[['INCIDENT_ID', 'OFFENSE_ID', 'OFFENSE_CODE', 'OFFENSE_TYPE_ID', 'OFFENSE_CATEGORY_ID', 'REPORTED_DATE', 'GEO_LON', 'GEO_LAT', 'NEIGHBORHOOD_ID']]
crime_2_df.head()

,INCIDENT_ID,OFFENSE_ID,OFFENSE_CODE,OFFENSE_TYPE_ID,OFFENSE_CATEGORY_ID,REPORTED_DATE,GEO_LON,GEO_LAT,NEIGHBORHOOD_ID
0,2.019279e+08,2.020000e+14,1208,robbery-residence,robbery,1/13/2019 14:41,-104.888750,39.739854,east-colfax
1,2.019238e+08,2.020000e+14,2404,theft-of-motor-vehicle,auto-theft,1/11/2019 10:06,-105.031119,39.764540,west-highland
2,2.019260e+08,2.020000e+14,2303,theft-shoplift,larceny,1/12/2019 12:01,-104.959055,39.740330,city-park
3,2.019600e+10,2.020000e+16,2999,criminal-mischief-mtr-veh,public-disorder,1/12/2019 14:04,-104.825985,39.797799,montbello
4,2.019291e+08,2.020000e+14,3504,drug-hallucinogen-possess,drug-alcohol,1/13/2019 23:46,-105.015348,39.730808,lincoln-park

In [21]:
# number of crimes in denver per category (not sure difference between incident id and offense id)
crimes_by_category_df = crime_2_df.groupby('OFFENSE_CATEGORY_ID')[['INCIDENT_ID', 'OFFENSE_ID']].nunique()
crimes_by_category_df

                              INCIDENT_ID  OFFENSE_ID
OFFENSE_CATEGORY_ID
aggravated-assault                   1062           5
all-other-crimes                     4805           7
arson                                  47           4
auto-theft                           2583           5
burglary                             1688           5
drug-alcohol                         2387           5
larceny                              4471           5
murder                                 27           3
other-crimes-against-persons         2197           6
public-disorder                      3711           6
robbery                               530           5
sexual-assault                        400           4
theft-from-motor-vehicle             3721           5
white-collar-crime                    621           4

In [22]:
# number of crimes per neighborhood (sorted least reported crime to most)
crimes_by_neighborhood_df = crime_2_df.groupby('NEIGHBORHOOD_ID')[['INCIDENT_ID', 'OFFENSE_ID']].nunique()
crimes_by_neighborhood_df.sort_values('OFFENSE_ID').head()

                 INCIDENT_ID  OFFENSE_ID
NEIGHBORHOOD_ID
wellshire                 28           3
city-park                174           3
barnum-west              180           3
country-club              51           3
jefferson-park           215           4

In [23]:
# number of crimes per neighborhood (viewing 5 neighborhoods with highest numbers of reported crimes)
crimes_by_neighborhood_df.sort_values('OFFENSE_ID').tail()

                   INCIDENT_ID  OFFENSE_ID
NEIGHBORHOOD_ID
athmar-park                295           5
montbello                  914           6
east-colfax                640           6
barnum                     240           6
harvey-park-south          219           6

In [24]:
pd.set_option('display.max_columns', None)
listings_gz_df = pd.read_csv('listings.csv.gz', compression = 'gzip', header = 0, sep = ',', quotechar = '"')
listings_gz_df.neighbourhood = listings_gz_df.neighbourhood.str.lower()
listings_gz_df.neighbourhood_cleansed = listings_gz_df.neighbourhood_cleansed.str.lower()
listings_gz_df.host_neighbourhood = listings_gz_df.host_neighbourhood.str.lower()
listings_gz_df.head()

,id,listing_url,scrape_id,last_scraped,name,summary,space,description,experiences_offered,neighborhood_overview,notes,transit,access,interaction,house_rules,thumbnail_url,medium_url,picture_url,xl_picture_url,host_id,host_url,host_name,host_since,host_location,host_about,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_thumbnail_url,host_picture_url,host_neighbourhood,host_listings_count,host_total_listings_count,host_verifications,host_has_profile_pic,host_identity_verified,street,neighbourhood,neighbourhood_cleansed,neighbourhood_group_cleansed,city,state,zipcode,market,smart_location,country_code,country,latitude,longitude,is_location_exact,property_type,room_type,accommodates,bathrooms,bedrooms,beds,bed_type,amenities,square_feet,price,weekly_price,monthly_price,security_deposit,cleaning_fee,guests_included,extra_people,minimum_nights,maximum_nights,minimum_minimum_nights,maximum_minimum_nights,minimum_maximum_nights,maximum_maximum_nights,minimum_nights_avg_ntm,maximum_nights_avg_ntm,calendar_updated,has_availability,availability_30,availability_60,availability_90,availability_365,calendar_last_scraped,number_of_reviews,number_of_reviews_ltm,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,requires_license,license,jurisdiction_names,instant_bookable,is_business_travel_ready,cancellation_policy,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,177,https://www.airbnb.com/rooms/177,20190427155417,2019-04-27,Tiny Home in the Heart of the City- ECO FRIENDLY,"160 sq ft + 80 sq ft loft for sleeping, Sleeps...",Here's the fun details of this Tiny Home exper...,"160 sq ft + 80 sq ft loft for sleeping, Sleeps...",none,"Quiet neighborhood next to park, creeks and bi...",STR Business File (In Photo Section) Lodger's ...,"Car is best, but public transportation is with...",The entire Tiny Home and shared back yard. Plu...,The Tiny Home is setup as self check-in. I'm a...,Please leave the east and west windows open a ...,NaN,NaN,https://a0.muscache.com/im/pictures/a1745ab2-b...,NaN,615,https://www.airbnb.com/users/show/615,Joe,2008-07-07,"Denver, Colorado, United States","I'm originally from Oklahoma, but have lived i...",within an hour,100%,NaN,t,https://a0.muscache.com/im/pictures/user/905d6...,https://a0.muscache.com/im/pictures/user/905d6...,virginia village,3.0,3.0,"['email', 'phone', 'google', 'reviews', 'kba']",t,t,"Denver, CO, United States",virginia village,virginia village,NaN,Denver,CO,80246.0,Denver,"Denver, CO",US,United States,39.69585,-104.92582,t,Guesthouse,Entire home/apt,2,1.0,1.0,1.0,Real Bed,"{TV,Wifi,""Air conditioning"",Kitchen,""Free park...",NaN,$56.00,NaN,NaN,"$1,500.00",$50.00,1,$15.00,1,400,1,1,400,400,1.0,400.0,today,t,0,0,0,0,2019-04-27,39,1,2016-09-04,2019-03-24,94.0,10.0,10.0,10.0,10.0,9.0,9.0,t,STR-2016-BFN-0004968,"{""Colorado State"","" the City and County of Den...",t,f,strict_14_with_grace_period,f,f,3,3,0,0,1.21
1,360,https://www.airbnb.com/rooms/360,20190427155417,2019-04-27,LoHi Secret garden at the Chickadee Cottage,Come enjoy our oasis is the city and stay at o...,Chickadee Cottage is the largest of our guest ...,Come enjoy our oasis is the city and stay at o...,none,those who are interested in our local brews - ...,WIFI: Once you have arrived you can find the...,there are several bus lines that cross the nei...,"Chickadee is the main the main property, sever...",We live on the property in the green house dir...,NUMBER ONE HOUSE RULE: please let us know ASAP...,NaN,NaN,https://a0.muscache.com/im/pictures/f622ba3c-c...,NaN,666,https://www.airbnb.com/users/show/666,Jennifer & Giovanni,2008-07-08,"Denver, Colorado, United States",We are a community of artists and tinkerers.\r...,within an hour,100%,NaN,t,https://a0.muscache.com/im/users/666/profile_p...,https://a0.muscache.com/im/users/666/profile_p...,highland,3.0,3.0,"['email', 'phone', 'facebook', 'reviews', 'jum...",t,t,"Denver, CO, United States",highland,highland,NaN,Denver,CO,80211.0,Denver,"Denver, CO",US,United States,39.76703,-105.00256,t,Guesthouse,Entire home/apt,5,1.0,2.0,2.0,Futon,"{TV,Wifi,""Air conditioning"",Kitchen,""Free stre...",NaN,$140.00,NaN,NaN,$150.00,$40.00,2,$15.00,1,29,1,2,29,29,1.1,29.0,3 days ago,t,10,20,34,290,2019-04-27,48,48,2018-08-13,2019-03-29,100.0,10.0,10.0,10.0,10.0,10.0,10.0,t,2017-BFN-0002177,"{""Colorado State"","" the City and County of Den...",t,f,moderate,t,t,3,3,0,0,5.58
2,590,https://www.airbnb.com/rooms/590,20190427155417,2019-04-27,Comfortable - and a great value!,"Large guest room in my home, where I also live...",I have been enjoying welcoming many wonderful ...,"Large guest room in my home, where I also live...",none,I love the diversity of my neighborhood and it...,Denver (and Colorado) now impose lodging tax o...,The number 20 RTD bus is 2 blocks away to go d...,You may make yourselves at home in all public ...,I am happy to interact as much or as little as...,NaN,NaN,NaN,https://a0.muscache.com/im/pictures/110931/309...,NaN,933,https://www.airbnb.com/users/show/933,Jill,2008-07-21,"Denver, Colorado, United States",I am friendly and I love meeting people from a...,within an hour,100%,NaN,t,https://a0.muscache.com/im/users/933/profile_p...,https://a0.muscache.com/im/users/933/profile_p...,north park hill,2.0,2.0,"['email', 'phone', 'facebook', 'reviews', 'jum...",t,t,"Denver, CO, United States",north park hill,north park hill,NaN,Denver,CO,80207.0,Denver,"Denver, CO",US,United States,39.75361,-104.91237,t,House,Private room,3,1.0,1.0,1.0,Real Bed,"{Internet,Wifi,""Air conditioning"",Kitchen,""Fre...",NaN,$61.00,$375.00,"$1,275.00",NaN,$10.00,1,$5.00,1,300,1,1,300,300,1.0,300.0,4 weeks ago,t,0,3,7,93,2019-04-27,565,40,2009-03-29,2019-03-27,97.0,10.0,10.0,10.0,10.0,10.0,10.0,t,2018-BFN-O0O5791,"{""Colorado State"","" the City and County of Den...",f,f,flexible,f,f,2,0,2,0,4.60
3,592,https://www.airbnb.com/rooms/592,20190427155417,2019-04-27,private,This room is in the basement. It does not hav...,This is a basement room. You can sometimes he...,This room is in the basement. It does not hav...,none,NaN,Denver (and Colorado) now impose lodging tax o...,It's convenient and easy to get here from the ...,Access to all public parts of the house - kitc...,I'm happy to interact with you if you wish. O...,No smoking in or near the house. I prefer n...,NaN,NaN,https://a0.muscache.com/im/pictures/110942/171...,NaN,933,https://www.airbnb.com/users/show/933,Jill,2008-07-21,"Denver, Colorado, United States",I am friendly and I love meeting people from a...,within an hour,100%,NaN,t,https://a0.muscache.com/im/users/933/profile_p...,https://a0.muscache.com/im/users/933/profile_p...,north park hill,2.0,2.0,"['email', 'phone', 'facebook', 'reviews', 'jum...",t,t,"Denver, CO, United States",north park hill,north park hill,NaN,Denver,CO,80207.0,Denver,"Denver, CO",US,United States,39.75438,-104.91156,t,House,Private room,2,1.0,1.0,1.0,Real Bed,"{Internet,Wifi,""Air conditioning"",Kitchen,""Fre...",NaN,$42.00,$295.00,$975.00,NaN,$10.00,1,$5.00,30,365,30,30,365,365,30.0,365.0,6 months ago,t,15,15,15,94,2019-04-27,147,5,2009-02-21,2019-03-22,97.0,9.0,9.0,10.0,10.0,10.0,10.0,t,2018-BFN-O0O5791,"{""Colorado State"","" the City and County of Den...",f,f,flexible,f,f,2,0,2,0,1.19
4,686,https://www.airbnb.com/rooms/686,20190427155417,2019-04-27,Alexandra's Uptown Queen Bed Room,Thank you for visiting my Queen Bed Room site!...,Thank you for checking out my Bed and Breakfas...,Thank you for visiting my Queen Bed Room site!...,none,"I love my Uptown neighborhood, which is within...",My STR license with the City and County of Den...,Getting around Denver is easy from here withou...,"Living room, dining room, kitchen, refrigerato...",I generally have a great deal of interaction w...,No smoking or vaping. No pets. If kitchen is u...,NaN,NaN,https://a0.muscache.com/im/pictures/108112/e6d...,NaN,990,https://www.airbnb.com/users/show/990,Alexandra,2008-07-23,"Denver, Colorado, United States","Denver native, former teacher, musician, chapl...",within an hour,100%,NaN,f,https://a0.muscache.com/im/pictures/c7c053dd-d...,https://a0.muscache.com/im/pictures/c7c053dd-d...,north capitol hill,2.0,2.0,"['email', 'phone', 'reviews', 'kba']",t,t,"Denver, CO, United States",north capitol hill,north capitol hill,NaN,Denver,CO,80203.0,Denver,"Denver, CO",US,United States,39.74503,-104.97756,t,House,Private room,2,2.0,1.0,1.0,Real Bed,"{TV,""Cable TV"",Internet,Wifi,""Air conditioning...",NaN,$70.00,NaN,"$1,470.00",$0.00,$10.00,1,$0.00,2,180,2,2,180,180,2.0,180.0,2 days ago,t,19,49,69,344,2019-04-27,236,13,2008-08-28,2019-04-16,95.0,10.0,10.0,10.0,10.0,10.0,10.0,t,2016-BFN-0008368,"{""Colorado State"","" the City and County of Den...",t,f,moderate,f,f,2,0,2,0,1.82

In [25]:
list(listings_gz_df)

['id',
 'listing_url',
 'scrape_id',
 'last_scraped',
 'name',
 'summary',
 'space',
 'description',
 'experiences_offered',
 'neighborhood_overview',
 'notes',
 'transit',
 'access',
 'interaction',
 'house_rules',
 'thumbnail_url',
 'medium_url',
 'picture_url',
 'xl_picture_url',
 'host_id',
 'host_url',
 'host_name',
 'host_since',
 'host_location',
 'host_about',
 'host_response_time',
 'host_response_rate',
 'host_acceptance_rate',
 'host_is_superhost',
 'host_thumbnail_url',
 'host_picture_url',
 'host_neighbourhood',
 'host_listings_count',
 'host_total_listings_count',
 'host_verifications',
 'host_has_profile_pic',
 'host_identity_verified',
 'street',
 'neighbourhood',
 'neighbourhood_cleansed',
 'neighbourhood_group_cleansed',
 'city',
 'state',
 'zipcode',
 'market',
 'smart_location',
 'country_code',
 'country',
 'latitude',
 'longitude',
 'is_location_exact',
 'property_type',
 'room_type',
 'accommodates',
 'bathrooms',
 'bedrooms',
 'beds',
 'bed_type',
 'amenities',
 'square_feet',
 'price',
 'weekly_price',
 'monthly_price',
 'security_deposit',
 'cleaning_fee',
 'guests_included',
 'extra_people',
 'minimum_nights',
 'maximum_nights',
 'minimum_minimum_nights',
 'maximum_minimum_nights',
 'minimum_maximum_nights',
 'maximum_maximum_nights',
 'minimum_nights_avg_ntm',
 'maximum_nights_avg_ntm',
 'calendar_updated',
 'has_availability',
 'availability_30',
 'availability_60',
 'availability_90',
 'availability_365',
 'calendar_last_scraped',
 'number_of_reviews',
 'number_of_reviews_ltm',
 'first_review',
 'last_review',
 'review_scores_rating',
 'review_scores_accuracy',
 'review_scores_cleanliness',
 'review_scores_checkin',
 'review_scores_communication',
 'review_scores_location',
 'review_scores_value',
 'requires_license',
 'license',
 'jurisdiction_names',
 'instant_bookable',
 'is_business_travel_ready',
 'cancellation_policy',
 'require_guest_profile_picture',
 'require_guest_phone_verification',
 'calculated_host_listings_count',
 'calculated_host_listings_count_entire_homes',
 'calculated_host_listings_count_private_rooms',
 'calculated_host_listings_count_shared_rooms',
 'reviews_per_month']

In [26]:
listings_df = pd.read_csv('listings.csv')
listings_df.neighbourhood = listings_df.neighbourhood.str.lower()
listings_df.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,177,Tiny Home in the Heart of the City- ECO FRIENDLY,615,Joe,NaN,virginia village,39.69585,-104.92582,Entire home/apt,56,1,39,2019-03-24,1.21,3,0
1,360,LoHi Secret garden at the Chickadee Cottage,666,Jennifer & Giovanni,NaN,highland,39.76703,-105.00256,Entire home/apt,140,1,48,2019-03-29,5.58,3,290
2,590,Comfortable - and a great value!,933,Jill,NaN,north park hill,39.75361,-104.91237,Private room,61,1,565,2019-03-27,4.60,2,93
3,592,private,933,Jill,NaN,north park hill,39.75438,-104.91156,Private room,42,30,147,2019-03-22,1.19,2,94
4,686,Alexandra's Uptown Queen Bed Room,990,Alexandra,NaN,north capitol hill,39.74503,-104.97756,Private room,70,2,236,2019-04-16,1.82,2,344

In [27]:
denver_2019_crime_df = pd.read_csv('denver_2019_crime.csv')

In [28]:
denver_2019_crime_df = denver_2019_crime_df[denver_2019_crime_df.OFFENSE_CATEGORY_ID != 'traffic-accident']

In [29]:
denver_2019_crime_df = denver_2019_crime_df[denver_2019_crime_df.OFFENSE_CATEGORY_ID != 'white-collar-crime']

In [30]:
denver_2019_crime_df.NEIGHBORHOOD_ID = denver_2019_crime_df.NEIGHBORHOOD_ID.str.replace("-"," ")

In [31]:
denver_2019_crime_df = denver_2019_crime_df.drop(columns=['OFFENSE_CODE_EXTENSION'])

In [32]:
denver_2019_crime_df.head()

,INCIDENT_ID,OFFENSE_ID,OFFENSE_CODE,OFFENSE_TYPE_ID,OFFENSE_CATEGORY_ID,FIRST_OCCURRENCE_DATE,LAST_OCCURRENCE_DATE,REPORTED_DATE,INCIDENT_ADDRESS,GEO_X,GEO_Y,GEO_LON,GEO_LAT,DISTRICT_ID,PRECINCT_ID,NEIGHBORHOOD_ID
0,2.019279e+08,2.020000e+14,1208,robbery-residence,robbery,1/12/2019 16:00,1/12/2019 19:00,1/13/2019 14:41,NaN,3171896.0,1694950.0,-104.888750,39.739854,2,223,east colfax
1,2.019238e+08,2.020000e+14,2404,theft-of-motor-vehicle,auto-theft,1/10/2019 18:30,1/11/2019 9:00,1/11/2019 10:06,3300 BLK W 34TH AVE,3131813.0,1703704.0,-105.031119,39.764540,1,113,west highland
2,2.019260e+08,2.020000e+14,2303,theft-shoplift,larceny,1/12/2019 11:30,NaN,1/12/2019 12:01,2341 E COLFAX AVE,3152124.0,1694998.0,-104.959055,39.740330,2,213,city park
3,2.019600e+10,2.020000e+16,2999,criminal-mischief-mtr-veh,public-disorder,1/12/2019 13:40,1/12/2019 13:40,1/12/2019 14:04,13891 E RANDOLPH PL,3189390.0,1716182.0,-104.825985,39.797799,5,521,montbello
4,2.019291e+08,2.020000e+14,3504,drug-hallucinogen-possess,drug-alcohol,1/13/2019 22:13,NaN,1/13/2019 23:46,I25 HWYNB / W 6TH AVE FWY,3136312.0,1691440.0,-105.015348,39.730808,1,123,lincoln park

In [33]:
from sqlalchemy import create_engine

engine = create_engine('sqlite:///all_denver_data.sqlite')

denver_2019_crime_df.to_sql(name='crime_2019', con=engine, if_exists='append', index=False)
reviews_gz_df.to_sql(name='reviews',con=engine, if_exists='append', index = False)
calendar_gz_df.to_sql(name='calendar',con=engine, if_exists='append', index = False)
listings_gz_df.to_sql(name='listings',con=engine, if_exists='append', index = False)